---
- name: Implementing host scope variables
  hosts: 172.31.23.241
  tasks:
    - name: User creation
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
...
