---
- name: Install docker on all servers
  hosts: all
  tasks:
    - name: Download the docker shell script
      shell: curl -fsSL https://get.docker.com -o install-docker.sh
    - name: Execute the above downloaded script
      shell: sudo sh install-docker.sh
...
