---
- name: Implementing Loops
  hosts: all
  tasks:
    - name: Install,uninstall,upgrade s/w applications
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: maven,b: present,c: no}
        - {a: git,b: absent,c: no}
        - {a: openjdk-17-jdk,b: latest,c: yes}
...
