---
- name: Install tomcat10 and restart it
  hosts: all
  tasks:
    - name: Install tomcat10
      apt:
        name: tomcat10
        state: present
        update_cache: yes
    - name: Restart tomcat10
      service:
        name: tomcat10
        state: restarted
...
